[package]
name = "example-websocket-chat"
version = "0.1.0"
edition.workspace = true
publish = false


[dependencies]
silent = { path = "../../silent", features = ["upgrade"] }
once_cell.workspace = true
async-lock = "3"
async-channel = "2"
